<?php
/**
 * सेटिंग schema: एडमिन → साइट सेटिंग के सभी टैब यहीं से बनते हैं।
 * नया सेटिंग = यहाँ एक पंक्ति। सिर्फ़ यहाँ लिखे key ही सेव होते हैं।
 *   type: text, textarea, email, url, tel, number, color, select, switch, image, code, checkboxes, timezone, font
 *   permission: 'edit' (settings.edit) या 'manage' (settings.manage: संवेदनशील)
 */
$fonts = ['Mukta' => 'Mukta', 'Noto Sans Devanagari' => 'Noto Sans Devanagari', 'Hind' => 'Hind', 'Baloo 2' => 'Baloo 2', 'Tiro Devanagari Hindi' => 'Tiro Devanagari Hindi (सेरिफ़)', 'Poppins' => 'Poppins', 'Inter' => 'Inter', 'Roboto' => 'Roboto'];

return [
    'general' => [
        'label' => 'सामान्य', 'icon' => 'fa-gear', 'permission' => 'edit',
        'fields' => [
            'site_name' => ['label' => 'वेबसाइट का नाम', 'type' => 'text', 'rules' => 'required|max:100', 'width' => 6],
            'tagline' => ['label' => 'टैगलाइन', 'type' => 'text', 'rules' => 'nullable|max:150', 'width' => 6],
            'site_description' => ['label' => 'वेबसाइट का विवरण', 'type' => 'textarea', 'rules' => 'nullable|max:300', 'help' => 'सर्च इंजन और सोशल मीडिया में दिखता है'],
            'language' => ['label' => 'मुख्य भाषा', 'type' => 'select', 'options' => ['hi' => 'हिंदी', 'en' => 'English'], 'default' => 'hi', 'rules' => 'required|in:hi,en', 'width' => 4],
            'timezone' => ['label' => 'टाइमज़ोन', 'type' => 'timezone', 'default' => 'Asia/Kolkata', 'rules' => 'required', 'width' => 4],
            'date_format' => ['label' => 'तारीख़ का प्रारूप', 'type' => 'select', 'options' => ['hindi' => '26 सितंबर 2026', 'd-m-Y' => '26-09-2026', 'd/m/Y' => '26/09/2026', 'M d, Y' => 'Sep 26, 2026'], 'default' => 'hindi', 'rules' => 'required', 'width' => 4],
        ],
    ],
    'branding' => [
        'label' => 'ब्रांडिंग', 'icon' => 'fa-palette', 'permission' => 'edit',
        'fields' => [
            'logo' => ['label' => 'लोगो', 'type' => 'image', 'help' => 'PNG/WebP, चौड़ाई 400-800px', 'width' => 4],
            'logo_dark' => ['label' => 'डार्क लोगो', 'type' => 'image', 'help' => 'गहरे बैकग्राउंड के लिए (सफ़ेद अक्षर)', 'width' => 4],
            'logo_mobile' => ['label' => 'मोबाइल लोगो', 'type' => 'image', 'help' => 'छोटा/चौकोर लोगो', 'width' => 4],
            'favicon' => ['label' => 'फ़ेविकॉन', 'type' => 'image', 'kind' => 'icon', 'help' => 'PNG 512×512', 'width' => 4],
            'primary_color' => ['label' => 'मुख्य रंग', 'type' => 'color', 'default' => '#d71920', 'rules' => 'required|color', 'width' => 4],
            'secondary_color' => ['label' => 'दूसरा रंग', 'type' => 'color', 'default' => '#15161a', 'rules' => 'required|color', 'width' => 4],
            'font_heading' => ['label' => 'शीर्षक का फ़ॉन्ट', 'type' => 'font', 'options' => $fonts, 'default' => 'Mukta', 'width' => 6],
            'font_body' => ['label' => 'लेख का फ़ॉन्ट', 'type' => 'font', 'options' => $fonts, 'default' => 'Noto Sans Devanagari', 'width' => 6],
        ],
    ],
    'contact' => [
        'label' => 'संपर्क', 'icon' => 'fa-address-card', 'permission' => 'edit',
        'fields' => [
            'contact_email' => ['label' => 'संपर्क ईमेल', 'type' => 'email', 'rules' => 'nullable|email|max:190', 'width' => 6],
            'contact_phone' => ['label' => 'फ़ोन नंबर', 'type' => 'tel', 'rules' => 'nullable|max:30', 'width' => 6],
            'whatsapp' => ['label' => 'WhatsApp नंबर', 'type' => 'tel', 'rules' => 'nullable|max:20', 'help' => 'देश कोड के साथ, जैसे 919876543210', 'width' => 6],
            'news_email' => ['label' => 'ख़बर भेजने का ईमेल', 'type' => 'email', 'rules' => 'nullable|email|max:190', 'width' => 6],
            'address' => ['label' => 'कार्यालय का पता', 'type' => 'textarea', 'rules' => 'nullable|max:300'],
            'map_url' => ['label' => 'Google Map लिंक', 'type' => 'url', 'rules' => 'nullable|url|max:500'],
        ],
    ],
    'social' => [
        'label' => 'सोशल मीडिया', 'icon' => 'fa-share-nodes', 'permission' => 'edit',
        'fields' => [
            'facebook' => ['label' => 'Facebook', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-facebook'],
            'twitter' => ['label' => 'X (Twitter)', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-x-twitter'],
            'youtube' => ['label' => 'YouTube', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-youtube'],
            'instagram' => ['label' => 'Instagram', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-instagram'],
            'telegram' => ['label' => 'Telegram', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-telegram'],
            'linkedin' => ['label' => 'LinkedIn', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-linkedin'],
            'whatsapp_channel' => ['label' => 'WhatsApp चैनल', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-whatsapp'],
            'sharechat' => ['label' => 'ShareChat / अन्य', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-solid fa-link'],
            'android_app' => ['label' => 'Android ऐप (Play Store)', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-google-play'],
            'ios_app' => ['label' => 'iOS ऐप (App Store)', 'type' => 'url', 'rules' => 'nullable|url|max:300', 'width' => 6, 'icon' => 'fa-brands fa-app-store-ios'],
        ],
    ],
    'layout' => [
        'label' => 'हेडर और फ़ुटर', 'icon' => 'fa-table-columns', 'permission' => 'edit',
        'fields' => [
            'show_topbar' => ['label' => 'ऊपर की पट्टी दिखाएँ (तारीख़, टॉप मेनू, सोशल)', 'type' => 'switch', 'default' => '1'],
            'show_date' => ['label' => 'आज की तारीख़ दिखाएँ', 'type' => 'switch', 'default' => '1'],
            'sticky_header' => ['label' => 'स्क्रॉल पर मेनू ऊपर चिपका रहे', 'type' => 'switch', 'default' => '1'],
            'show_header_ad' => ['label' => 'लोगो के पास विज्ञापन की जगह', 'type' => 'switch', 'default' => '1'],
            'footer_about' => ['label' => 'फ़ुटर में परिचय', 'type' => 'textarea', 'rules' => 'nullable|max:500'],
            'footer_newsletter' => ['label' => 'फ़ुटर में न्यूज़लेटर फ़ॉर्म', 'type' => 'switch', 'default' => '1'],
            'footer_apps' => ['label' => 'फ़ुटर में ऐप डाउनलोड लिंक', 'type' => 'switch', 'default' => '1'],
            'copyright_text' => ['label' => 'कॉपीराइट पंक्ति', 'type' => 'text', 'rules' => 'nullable|max:200', 'help' => '{year} और {site_name} अपने आप बदलेंगे', 'default' => '© {year} {site_name}। सर्वाधिकार सुरक्षित।'],
        ],
    ],
    'features' => [
        'label' => 'कंटेंट फ़ीचर', 'icon' => 'fa-toggle-on', 'permission' => 'edit',
        'fields' => [
            'breaking_ticker' => ['label' => 'ब्रेकिंग न्यूज़ पट्टी', 'type' => 'switch', 'default' => '1'],
            'trending_bar' => ['label' => 'ट्रेंडिंग पट्टी (फ़ीचर्ड टॉपिक + ट्रेंडिंग टैग)', 'type' => 'switch', 'default' => '1'],
            'ticker_speed' => ['label' => 'पट्टी की रफ़्तार', 'type' => 'select', 'options' => ['slow' => 'धीमी', 'medium' => 'सामान्य', 'fast' => 'तेज़'], 'default' => 'medium', 'width' => 6],
            'breaking_expiry_hours' => ['label' => 'ब्रेकिंग अपने आप कितने घंटे में हटे', 'type' => 'number', 'default' => '6', 'rules' => 'required|integer|min:0|max:720', 'width' => 6, 'help' => 'कंट्रोल रूम में नए आइटम का डिफ़ॉल्ट; 0 = हाथ से हटाने तक'],
            'live_blog_refresh' => ['label' => 'लाइव ब्लॉग: नए अपडेट की जाँच (सेकंड)', 'type' => 'number', 'default' => '30', 'rules' => 'required|integer|min:15|max:300', 'width' => 6],
            'live_show_author' => ['label' => 'लाइव अपडेट पर लिखने वाले का नाम', 'type' => 'switch', 'default' => '1', 'width' => 6],
            'comments_enabled' => ['label' => 'पाठकों की टिप्पणियाँ', 'type' => 'switch', 'default' => '1'],
            'comments_moderation' => ['label' => 'टिप्पणी मंज़ूरी के बाद दिखे', 'type' => 'switch', 'default' => '1'],
            'share_buttons' => ['label' => 'शेयर बटन', 'type' => 'checkboxes', 'options' => ['whatsapp' => 'WhatsApp', 'facebook' => 'Facebook', 'x' => 'X', 'telegram' => 'Telegram', 'linkedin' => 'LinkedIn', 'copy' => 'लिंक कॉपी', 'native' => 'मोबाइल शेयर'], 'default' => 'whatsapp,facebook,x,telegram,copy,native'],
            'author_box' => ['label' => 'ख़बर के नीचे लेखक बॉक्स', 'type' => 'switch', 'default' => '1'],
            'related_news' => ['label' => 'संबंधित ख़बरें', 'type' => 'switch', 'default' => '1'],
            'reading_time' => ['label' => 'पढ़ने का समय दिखाएँ', 'type' => 'switch', 'default' => '1'],
            'show_views' => ['label' => 'व्यूज़ की गिनती दिखाएँ', 'type' => 'switch', 'default' => '0'],
            'posts_per_page' => ['label' => 'एक पेज पर ख़बरें', 'type' => 'number', 'default' => '12', 'rules' => 'required|integer|min:5|max:60', 'width' => 6],
        ],
    ],
    'media' => [
        'label' => 'लाइव टीवी और ई-पेपर', 'icon' => 'fa-tv', 'permission' => 'edit',
        'fields' => [
            'live_tv_url' => ['label' => 'लाइव टीवी (YouTube लाइव लिंक)', 'type' => 'url', 'rules' => 'nullable|url|max:500', 'help' => 'सिर्फ़ तब इस्तेमाल होता है जब "लाइव टीवी" मॉड्यूल में कोई चालू चैनल न हो'],
            'epaper_enabled' => ['label' => 'ई-पेपर दिखाएँ', 'type' => 'switch', 'default' => '1'],
            'epaper_pdf_download' => ['label' => 'ई-पेपर: पाठक PDF डाउनलोड कर सकें (सिर्फ़ मुफ़्त अंक)', 'type' => 'switch', 'default' => '1'],
            'epaper_free_pages' => ['label' => 'प्रीमियम अंक में सबके लिए खुले पेज', 'type' => 'number', 'default' => '2', 'rules' => 'required|integer|min:0|max:50', 'width' => 6, 'help' => 'बाकी पेज स्टाफ़ को; पाठक सदस्यता Phase 11 में'],
            'epaper_max_pdf_mb' => ['label' => 'PDF की अधिकतम साइज़ (MB)', 'type' => 'number', 'default' => '50', 'rules' => 'required|integer|min:1|max:500', 'width' => 6, 'help' => 'सर्वर की अपलोड सीमा से ज़्यादा नहीं हो सकती'],
        ],
    ],
    'ads' => [
        'label' => 'विज्ञापन और बिलिंग', 'icon' => 'fa-rectangle-ad', 'permission' => 'edit',
        'fields' => [
            'ads_enabled' => ['label' => 'वेबसाइट पर विज्ञापन दिखाएँ', 'type' => 'switch', 'default' => '1'],
            'ads_label' => ['label' => 'विज्ञापन के ऊपर लेबल', 'type' => 'text', 'default' => 'विज्ञापन', 'rules' => 'nullable|max:30', 'width' => 6],
            'ads_inline_after' => ['label' => 'ख़बर में कितने पैराग्राफ़ बाद "बीच का" विज्ञापन', 'type' => 'number', 'default' => '3', 'rules' => 'required|integer|min:1|max:20', 'width' => 6],
            'ads_popup_hours' => ['label' => 'पॉपअप एक पाठक को कितने घंटे में एक बार', 'type' => 'number', 'default' => '24', 'rules' => 'required|integer|min:1|max:720', 'width' => 6],
            'ads_popup_delay' => ['label' => 'पॉपअप कितने सेकंड बाद खुले', 'type' => 'number', 'default' => '5', 'rules' => 'required|integer|min:0|max:120', 'width' => 6],
            'billing_name' => ['label' => 'इनवॉइस पर कंपनी का नाम', 'type' => 'text', 'rules' => 'nullable|max:190', 'help' => 'ख़ाली = साइट का नाम'],
            'billing_address' => ['label' => 'इनवॉइस पर पता', 'type' => 'textarea', 'rules' => 'nullable|max:500'],
            'billing_gstin' => ['label' => 'GSTIN', 'type' => 'text', 'rules' => 'nullable|max:20', 'width' => 6],
            'billing_tax_rate' => ['label' => 'डिफ़ॉल्ट GST (%)', 'type' => 'number', 'default' => '18', 'rules' => 'required|numeric|min:0|max:50', 'width' => 6],
            'billing_terms' => ['label' => 'इनवॉइस के नीचे शर्तें / बैंक विवरण', 'type' => 'textarea', 'rules' => 'nullable|max:1000'],
        ],
    ],
    'images' => [
        'label' => 'इमेज और वॉटरमार्क', 'icon' => 'fa-image', 'permission' => 'edit',
        'fields' => [
            'media_large_width' => ['label' => 'बड़ी इमेज की चौड़ाई (px)', 'type' => 'number', 'default' => '1600', 'rules' => 'required|integer|min:800|max:4000', 'width' => 4, 'help' => 'लेख में दिखने वाली सबसे बड़ी इमेज'],
            'media_quality' => ['label' => 'इमेज क्वालिटी (50-95)', 'type' => 'number', 'default' => '82', 'rules' => 'required|integer|min:50|max:95', 'width' => 4, 'help' => 'कम = हल्की फ़ाइल, तेज़ वेबसाइट'],
            'media_webp' => ['label' => 'WebP भी बनाएँ (तेज़ लोडिंग; सर्वर पर उपलब्ध हो तो)', 'type' => 'switch', 'default' => '1'],
            'watermark_enabled' => ['label' => 'नई इमेज पर वॉटरमार्क लगाएँ (मूल फ़ाइल पर नहीं, सिर्फ़ बड़ी/मध्यम कॉपी पर)', 'type' => 'switch', 'default' => '0'],
            'watermark_type' => ['label' => 'वॉटरमार्क का प्रकार', 'type' => 'select', 'options' => ['image' => 'लोगो (PNG)', 'text' => 'टेक्स्ट'], 'default' => 'image', 'rules' => 'required|in:image,text', 'width' => 4],
            'watermark_position' => ['label' => 'जगह', 'type' => 'select', 'options' => ['bottom-right' => 'नीचे दाएँ', 'bottom-left' => 'नीचे बाएँ', 'top-right' => 'ऊपर दाएँ', 'top-left' => 'ऊपर बाएँ', 'center' => 'बीच में'], 'default' => 'bottom-right', 'rules' => 'required|in:bottom-right,bottom-left,top-right,top-left,center', 'width' => 4],
            'watermark_opacity' => ['label' => 'दिखने की तीव्रता (10-100%)', 'type' => 'number', 'default' => '60', 'rules' => 'required|integer|min:10|max:100', 'width' => 4],
            'watermark_image' => ['label' => 'वॉटरमार्क लोगो', 'type' => 'image', 'help' => 'पारदर्शी PNG सबसे अच्छा', 'width' => 6],
            'watermark_text' => ['label' => 'वॉटरमार्क टेक्स्ट', 'type' => 'text', 'rules' => 'nullable|max:60|regex:/^[\x20-\x7E]*$/', 'placeholder' => 'www.example.com', 'help' => 'सिर्फ़ अंग्रेज़ी अक्षर/अंक (हिंदी के लिए लोगो वाला वॉटरमार्क चुनें)', 'width' => 6],
        ],
    ],
    'reporters' => [
        'label' => 'रिपोर्टर और ID कार्ड', 'icon' => 'fa-id-card', 'permission' => 'edit',
        'fields' => [
            'join_enabled' => ['label' => '“रिपोर्टर बनें” फ़ॉर्म चालू (/join-as-reporter)', 'type' => 'switch', 'default' => '1'],
            'join_intro' => ['label' => 'फ़ॉर्म के ऊपर परिचय', 'type' => 'textarea', 'rules' => 'nullable|max:1000', 'default' => 'हमारे साथ जुड़कर अपने क्षेत्र की ख़बरें दुनिया तक पहुँचाएँ। सभी खाने सही भरें और दस्तावेज़ साफ़ अपलोड करें।'],
            'join_declaration' => ['label' => 'घोषणा (आवेदक को स्वीकार करनी होगी)', 'type' => 'textarea', 'rules' => 'nullable|max:2000', 'default' => 'मैं घोषणा करता/करती हूँ कि दी गई सभी जानकारी और दस्तावेज़ सही हैं। मैं संस्थान की संपादकीय नीति, आचार संहिता और रिपोर्टर नीति का पालन करूँगा/करूँगी। ग़लत जानकारी पाए जाने पर आवेदन या नियुक्ति रद्द की जा सकती है।'],
            'reporter_id_prefix' => ['label' => 'रिपोर्टर ID का शुरुआती हिस्सा', 'type' => 'text', 'default' => 'RPT', 'rules' => 'required|max:8|regex:/^[A-Z]{2,8}$/', 'width' => 4, 'help' => 'जैसे RPT → RPT-2026-0001'],
            'reporter_validity_months' => ['label' => 'ID कार्ड की वैधता (महीने)', 'type' => 'number', 'default' => '12', 'rules' => 'required|integer|min:1|max:60', 'width' => 4],
            'signatory_name' => ['label' => 'हस्ताक्षरकर्ता का नाम', 'type' => 'text', 'rules' => 'nullable|max:100', 'width' => 6],
            'signatory_designation' => ['label' => 'हस्ताक्षरकर्ता का पद', 'type' => 'text', 'default' => 'प्रधान संपादक', 'rules' => 'nullable|max:100', 'width' => 6],
            'signature_image' => ['label' => 'हस्ताक्षर (पारदर्शी PNG)', 'type' => 'image', 'width' => 6],
            'stamp_image' => ['label' => 'मुहर (पारदर्शी PNG)', 'type' => 'image', 'width' => 6],
            'registration_no' => ['label' => 'पंजीकरण संख्या (पत्रों में)', 'type' => 'text', 'rules' => 'nullable|max:100', 'width' => 6],
            'id_card_show_mobile' => ['label' => 'ID कार्ड के आगे रिपोर्टर का मोबाइल दिखाएँ', 'type' => 'switch', 'default' => '1', 'width' => 6],
            'id_card_show_address' => ['label' => 'ID कार्ड के आगे रिपोर्टर का पता दिखाएँ', 'type' => 'switch', 'default' => '1', 'width' => 6],
            'id_card_note' => ['label' => 'ID कार्ड के पीछे का नोट', 'type' => 'textarea', 'rules' => 'nullable|max:300', 'default' => 'यह कार्ड संस्थान की संपत्ति है। मिलने पर ऊपर दिए पते पर लौटाएँ। सत्यापन के लिए QR स्कैन करें।'],
        ],
    ],
    'analytics' => [
        'label' => 'एनालिटिक्स और कोड', 'icon' => 'fa-code', 'permission' => 'manage',
        'fields' => [
            'ga_id' => ['label' => 'Google Analytics 4 ID', 'type' => 'text', 'rules' => 'nullable|regex:/^G-[A-Z0-9]{4,20}$/', 'placeholder' => 'G-XXXXXXXXXX', 'width' => 6],
            'gtm_id' => ['label' => 'Google Tag Manager ID', 'type' => 'text', 'rules' => 'nullable|regex:/^GTM-[A-Z0-9]{4,12}$/', 'placeholder' => 'GTM-XXXXXXX', 'width' => 6],
            'search_console' => ['label' => 'Google Search Console verification', 'type' => 'text', 'rules' => 'nullable|max:120', 'help' => 'सिर्फ़ content="…" वाला मान'],
            'header_code' => ['label' => '<head> में अतिरिक्त कोड', 'type' => 'code', 'help' => 'सिर्फ़ भरोसेमंद कोड (जैसे AdSense)। हर बदलाव ऑडिट लॉग में दर्ज होता है।'],
            'footer_code' => ['label' => '</body> से पहले अतिरिक्त कोड', 'type' => 'code'],
            // Phase 13: अपना एनालिटिक्स और ट्रेंडिंग
            'analytics_enabled' => ['label' => 'साइट का अपना एनालिटिक्स (पेज व्यू, विज़िटर, रियलटाइम)', 'type' => 'switch', 'default' => '1', 'width' => 6, 'help' => 'कुकी के बिना; IP सेव नहीं होता।'],
            'analytics_exclude_staff' => ['label' => 'लॉग-इन स्टाफ़ के व्यू न गिनें', 'type' => 'switch', 'default' => '1', 'width' => 6],
            'analytics_raw_days' => ['label' => 'हर व्यू का ब्योरा कितने दिन रखें', 'type' => 'number', 'rules' => 'required|integer|min:3|max:365', 'default' => '35', 'width' => 4, 'help' => 'उसके बाद सिर्फ़ रोज़ का सारांश रहता है।'],
            'trending_hours' => ['label' => 'ट्रेंडिंग: कितने घंटे के व्यू/शेयर', 'type' => 'number', 'rules' => 'required|integer|min:3|max:168', 'default' => '24', 'width' => 4],
            'trending_max_days' => ['label' => 'ट्रेंडिंग: ख़बर अधिकतम कितने दिन पुरानी', 'type' => 'number', 'rules' => 'required|integer|min:1|max:60', 'default' => '7', 'width' => 4],
        ],
    ],
    'seo' => [
        'label' => 'SEO', 'icon' => 'fa-magnifying-glass-chart', 'permission' => 'seo.edit',
        'fields' => [
            'seo_separator' => ['label' => 'शीर्षक का विभाजक', 'type' => 'select', 'options' => ['|' => 'ख़बर | साइट', '-' => 'ख़बर - साइट', '–' => 'ख़बर – साइट', '·' => 'ख़बर · साइट', '' => 'सिर्फ़ ख़बर का शीर्षक'], 'default' => '|', 'rules' => ['nullable', 'in:|,-,–,·'], 'width' => 6],
            'seo_publication' => ['label' => 'Google News में प्रकाशन का नाम', 'type' => 'text', 'rules' => 'nullable|max:120', 'width' => 6, 'help' => 'ख़ाली = साइट का नाम। Publisher Center वाला नाम ही लिखें।'],
            'seo_home_title' => ['label' => 'होमपेज का SEO शीर्षक', 'type' => 'text', 'rules' => 'nullable|max:120', 'help' => 'ख़ाली = "साइट का नाम | टैगलाइन"'],
            'seo_home_description' => ['label' => 'होमपेज का SEO विवरण', 'type' => 'textarea', 'rules' => 'nullable|max:320', 'help' => 'ख़ाली = साइट का विवरण (सामान्य टैब)'],
            'seo_og_image' => ['label' => 'डिफ़ॉल्ट शेयर इमेज (1200×630)', 'type' => 'image', 'width' => 6, 'help' => 'जिस पेज की अपनी इमेज न हो, उसे WhatsApp/Facebook पर शेयर करने पर यह दिखेगी'],
            'seo_twitter' => ['label' => 'X (Twitter) हैंडल', 'type' => 'text', 'rules' => ['nullable', 'regex:/^@?[A-Za-z0-9_]{1,15}$/'], 'placeholder' => '@yournews', 'width' => 3],
            'seo_fb_app_id' => ['label' => 'Facebook App ID', 'type' => 'text', 'rules' => 'nullable|regex:/^[0-9]{5,20}$/', 'width' => 3],
            'seo_bing' => ['label' => 'Bing verification', 'type' => 'text', 'rules' => 'nullable|max:120', 'width' => 6, 'help' => 'msvalidate.01 का content मान'],
            'seo_yandex' => ['label' => 'Yandex verification', 'type' => 'text', 'rules' => 'nullable|max:120', 'width' => 6],
            'seo_canonical_host' => ['label' => 'मुख्य डोमेन (canonical)', 'type' => 'url', 'rules' => 'nullable|url|max:190', 'placeholder' => 'https://www.yournews.com', 'help' => 'ख़ाली = इंस्टॉल वाला पता। www / बिना www में से एक चुनें; canonical, साइटमैप और शेयर लिंक इसी से बनेंगे।'],
            'seo_image_preview' => ['label' => 'Google Discover के लिए बड़ी इमेज प्रीव्यू (max-image-preview:large)', 'type' => 'switch', 'default' => '1'],
            'seo_noindex_tags' => ['label' => 'टैग पेज noindex (कम ख़बरों वाले टैग पेज Google में न जाएँ)', 'type' => 'switch', 'default' => '0'],
            'seo_auto_redirect' => ['label' => 'स्लग बदलने पर पुराने पते से नए पर अपने आप 301 रीडायरेक्ट', 'type' => 'switch', 'default' => '1'],
            'seo_log_404' => ['label' => '404 (न मिले पेज) दर्ज करें', 'type' => 'switch', 'default' => '1'],
            'sitemap_news' => ['label' => 'Google News साइटमैप', 'type' => 'switch', 'default' => '1'],
            'sitemap_videos' => ['label' => 'वीडियो साइटमैप', 'type' => 'switch', 'default' => '1'],
            'sitemap_images' => ['label' => 'इमेज साइटमैप (गैलरी) और ख़बरों में इमेज', 'type' => 'switch', 'default' => '1'],
        ],
    ],
    'seo_robots' => [
        'label' => 'robots.txt', 'icon' => 'fa-robot', 'permission' => 'seo.manage',
        'fields' => [
            'robots_block_ai' => ['label' => 'AI ट्रेनिंग क्रॉलर रोकें (GPTBot, CCBot, Google-Extended, ClaudeBot आदि)', 'type' => 'switch', 'default' => '0', 'help' => 'Google Search और Google News पर असर नहीं पड़ता।'],
            'robots_extra' => ['label' => 'robots.txt में अतिरिक्त नियम', 'type' => 'code', 'rules' => 'nullable|max:5000', 'help' => 'जैसे: Disallow: /print/ — सावधान: "Disallow: /" पूरी साइट Google से हटा देगा।'],
        ],
    ],
    'audience' => [
        'label' => 'पाठक और टिप्पणियाँ', 'icon' => 'fa-user-group', 'permission' => 'manage',
        'fields' => [
            'readers_enabled' => ['label' => 'पाठक खाते चालू (लॉगिन, सेव, फ़ॉलो, "आपके लिए")', 'type' => 'switch', 'default' => '1'],
            'readers_verify_email' => ['label' => 'रजिस्टर पर ईमेल सत्यापन ज़रूरी', 'type' => 'switch', 'default' => '1', 'help' => 'बंद करें सिर्फ़ तब, जब सर्वर से ईमेल न जाता हो।'],
            'comments_enabled' => ['label' => 'ख़बरों पर टिप्पणियाँ चालू', 'type' => 'switch', 'default' => '1'],
            'comments_who' => ['label' => 'कौन टिप्पणी कर सकता है', 'type' => 'select', 'options' => ['guests' => 'कोई भी (नाम + ईमेल)', 'readers' => 'सिर्फ़ लॉगिन पाठक'], 'default' => 'guests', 'width' => 6],
            'comments_moderation' => ['label' => 'मॉडरेशन', 'type' => 'select', 'options' => ['all' => 'हर टिप्पणी पहले जाँच (सुझाया)', 'trusted' => 'भरोसेमंद पाठक सीधे, बाकी जाँच', 'none' => 'सब सीधे (स्पैम को छोड़कर)'], 'default' => 'all', 'width' => 6],
            'comments_close_days' => ['label' => 'कितने दिन बाद टिप्पणी बंद (0 = कभी नहीं)', 'type' => 'number', 'default' => '0', 'rules' => 'required|integer|min:0|max:3650', 'width' => 4],
            'comments_min_seconds' => ['label' => 'फ़ॉर्म भरने का कम से कम समय (सेकंड, बॉट रोक)', 'type' => 'number', 'default' => '5', 'rules' => 'required|integer|min:0|max:120', 'width' => 4],
            'comments_max_links' => ['label' => 'इससे ज़्यादा लिंक = स्पैम', 'type' => 'number', 'default' => '2', 'rules' => 'required|integer|min:0|max:20', 'width' => 4],
            'comments_blocked_words' => ['label' => 'रोके गए शब्द (एक लाइन में एक या कॉमा से)', 'type' => 'textarea', 'rules' => 'nullable|max:5000', 'help' => 'ऐसे शब्द वाली टिप्पणी सीधे स्पैम में जाएगी।'],
            'complaint_tracking' => ['label' => 'शिकायत की सार्वजनिक ट्रैकिंग (नंबर + मोबाइल/ईमेल से स्थिति)', 'type' => 'switch', 'default' => '1'],
            'newsletter_enabled' => ['label' => 'न्यूज़लेटर फ़ॉर्म चालू', 'type' => 'switch', 'default' => '1'],
            'newsletter_double_optin' => ['label' => 'डबल ऑप्ट-इन (ईमेल पर पुष्टि के बाद ही सब्सक्राइब)', 'type' => 'switch', 'default' => '1'],
            'newsletter_batch' => ['label' => 'हर मिनट कितने ईमेल भेजें', 'type' => 'number', 'default' => '30', 'rules' => 'required|integer|min:1|max:500', 'width' => 6, 'help' => 'होस्टिंग की ईमेल सीमा देखकर (जैसे 300/घंटा = 5)'],
        ],
    ],
    'notify' => [
        'label' => 'नोटिफ़िकेशन', 'icon' => 'fa-bell', 'permission' => 'notifications.manage',
        'fields' => [
            'push_enabled' => ['label' => 'वेब पुश चालू (पाठकों से अनुमति माँगें)', 'type' => 'switch', 'default' => '0', 'help' => 'HTTPS ज़रूरी है। कुंजियाँ (VAPID) अपने आप बनती हैं।'],
            'push_prompt' => ['label' => 'पुश के लिए संदेश', 'type' => 'text', 'default' => 'ब्रेकिंग न्यूज़ सबसे पहले पाएँ', 'rules' => 'nullable|max:120'],
            'notify_breaking' => ['label' => 'ब्रेकिंग न्यूज़', 'type' => 'checkboxes', 'options' => ['push' => 'वेब पुश', 'inapp' => 'पाठक खाता', 'email' => 'ईमेल', 'sms' => 'SMS', 'whatsapp' => 'WhatsApp'], 'default' => 'push,inapp'],
            'notify_epaper' => ['label' => 'ई-पेपर प्रकाशित', 'type' => 'checkboxes', 'options' => ['push' => 'वेब पुश', 'inapp' => 'पाठक खाता', 'email' => 'ईमेल'], 'default' => 'push,inapp'],
            'notify_followed' => ['label' => 'फ़ॉलो की गई चीज़ की नई ख़बर', 'type' => 'checkboxes', 'options' => ['inapp' => 'पाठक खाता', 'email' => 'ईमेल'], 'default' => 'inapp'],
            'notify_news_approved' => ['label' => 'ख़बर स्वीकृत/प्रकाशित (रिपोर्टर को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी', 'email' => 'ईमेल', 'sms' => 'SMS', 'whatsapp' => 'WhatsApp'], 'default' => 'inapp,email'],
            'notify_news_returned' => ['label' => 'ख़बर लौटाई/अस्वीकृत (रिपोर्टर को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी', 'email' => 'ईमेल', 'sms' => 'SMS', 'whatsapp' => 'WhatsApp'], 'default' => 'inapp,email'],
            'notify_news_submitted' => ['label' => 'नई ख़बर जाँच के लिए (डेस्क को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी', 'email' => 'ईमेल'], 'default' => 'inapp'],
            'notify_assignment' => ['label' => 'नया असाइनमेंट (रिपोर्टर को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी', 'email' => 'ईमेल', 'sms' => 'SMS', 'whatsapp' => 'WhatsApp'], 'default' => 'inapp,email'],
            'notify_reporter_approved' => ['label' => 'रिपोर्टर आवेदन स्वीकृत (ईमेल अलग से जाता है)', 'type' => 'checkboxes', 'options' => ['sms' => 'SMS', 'whatsapp' => 'WhatsApp'], 'default' => ''],
            'notify_document_expiry' => ['label' => 'रिपोर्टर की वैधता ख़त्म होने वाली', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी', 'email' => 'ईमेल', 'sms' => 'SMS', 'whatsapp' => 'WhatsApp'], 'default' => 'inapp,email'],
            'notify_comment' => ['label' => 'नई टिप्पणी (मॉडरेटर को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी'], 'default' => 'inapp'],
            'notify_comment_reply' => ['label' => 'टिप्पणी स्वीकृत/जवाब (पाठक को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'पाठक खाता', 'email' => 'ईमेल'], 'default' => 'inapp'],
            'notify_form' => ['label' => 'नया फ़ॉर्म जमा (संपर्क/टिप/शिकायत/आवेदन, टीम को)', 'type' => 'checkboxes', 'options' => ['inapp' => 'घंटी', 'email' => 'ईमेल'], 'default' => 'inapp'],
            'notify_manual' => ['label' => 'हाथ से भेजी सूचना', 'type' => 'checkboxes', 'options' => ['push' => 'वेब पुश', 'inapp' => 'पाठक खाता', 'email' => 'ईमेल'], 'default' => 'push'],
            'sms_driver' => ['label' => 'SMS ड्राइवर', 'type' => 'select', 'options' => ['off' => 'बंद', 'log' => 'सिर्फ़ लॉग (टेस्ट)', 'http' => 'अपना प्रोवाइडर (HTTP API)'], 'default' => 'off', 'width' => 4],
            'sms_http_url' => ['label' => 'SMS API URL', 'type' => 'text', 'rules' => 'nullable|max:500', 'width' => 8, 'placeholder' => 'https://api.provider.com/send?to={to}&text={message}', 'help' => '{to}, {message}, {url} अपने आप भरेंगे'],
            'sms_http_body' => ['label' => 'SMS JSON बॉडी (वैकल्पिक; हो तो POST)', 'type' => 'code', 'rules' => 'nullable|max:2000'],
            'sms_http_headers' => ['label' => 'SMS हेडर (एक लाइन में एक, जैसे Authorization: Bearer …)', 'type' => 'code', 'rules' => 'nullable|max:1000'],
            'whatsapp_driver' => ['label' => 'WhatsApp ड्राइवर', 'type' => 'select', 'options' => ['off' => 'बंद', 'log' => 'सिर्फ़ लॉग (टेस्ट)', 'http' => 'अपना प्रोवाइडर (HTTP API)'], 'default' => 'off', 'width' => 4],
            'whatsapp_http_url' => ['label' => 'WhatsApp API URL', 'type' => 'text', 'rules' => 'nullable|max:500', 'width' => 8, 'placeholder' => 'https://api.provider.com/send?to={to}&text={message}', 'help' => '{to}, {message}, {url} अपने आप भरेंगे'],
            'whatsapp_http_body' => ['label' => 'WhatsApp JSON बॉडी (वैकल्पिक; हो तो POST)', 'type' => 'code', 'rules' => 'nullable|max:2000'],
            'whatsapp_http_headers' => ['label' => 'WhatsApp हेडर (एक लाइन में एक, जैसे Authorization: Bearer …)', 'type' => 'code', 'rules' => 'nullable|max:1000'],
        ],
    ],
    'mail' => [
        'label' => 'ईमेल', 'icon' => 'fa-envelope', 'permission' => 'manage',
        'fields' => [
            'mail_from_name' => ['label' => 'भेजने वाले का नाम', 'type' => 'text', 'rules' => 'nullable|max:100', 'width' => 6],
            'mail_from_email' => ['label' => 'भेजने वाला ईमेल', 'type' => 'email', 'rules' => 'nullable|email|max:190', 'width' => 6, 'help' => 'अपने डोमेन का ईमेल रखें (जैसे no-reply@yoursite.com)'],
        ],
    ],
    'security' => [
        'label' => 'सुरक्षा', 'icon' => 'fa-shield-halved', 'permission' => 'manage',
        'fields' => [
            'session_timeout' => ['label' => 'निष्क्रियता पर लॉगआउट (मिनट)', 'type' => 'number', 'default' => '120', 'rules' => 'required|integer|min:5|max:1440', 'width' => 4],
            'login_max_attempts' => ['label' => 'ग़लत लॉगिन प्रयास की सीमा', 'type' => 'number', 'default' => '5', 'rules' => 'required|integer|min:3|max:20', 'width' => 4],
            'login_lockout_minutes' => ['label' => 'रोक का समय (मिनट)', 'type' => 'number', 'default' => '15', 'rules' => 'required|integer|min:1|max:1440', 'width' => 4],
            'admin_ip_allowlist' => ['label' => 'एडमिन IP allowlist (वैकल्पिक)', 'type' => 'textarea', 'rules' => 'nullable|max:2000',
                'help' => 'ख़ाली = कहीं से भी। एक लाइन में एक IP या रेंज (जैसे 203.0.113.5 या 203.0.113.0/24)। स्टाफ़ सिर्फ़ इन्हीं IP से लॉगिन/काम कर सकेगा; रिपोर्टर पर लागू नहीं। फँस जाएँ तो config/env.php में ADMIN_IP_BYPASS = 1।'],
            'hsts' => ['label' => 'HTTPS पर HSTS हेडर भेजें', 'type' => 'switch', 'default' => '1', 'help' => 'ब्राउज़र हमेशा HTTPS से खोलेगा। सिर्फ़ तब चालू रखें जब SSL हमेशा रहेगा।'],
            'audit_retention_days' => ['label' => 'ऑडिट लॉग कितने दिन रखें', 'type' => 'number', 'default' => '365', 'rules' => 'required|integer|min:0|max:3650', 'width' => 4, 'help' => '0 = कभी न हटाएँ'],
            'log_retention_days' => ['label' => 'एरर/मेल लॉग फ़ाइलें कितने दिन', 'type' => 'number', 'default' => '30', 'rules' => 'required|integer|min:3|max:365', 'width' => 4],
            'slow_request_ms' => ['label' => 'धीमा अनुरोध (मिलीसेकंड से ज़्यादा)', 'type' => 'number', 'default' => '1500', 'rules' => 'required|integer|min:200|max:30000', 'width' => 4],
            'separate_reporter_login' => ['label' => 'रिपोर्टर और स्टाफ़ के लॉगिन पेज अलग रखें', 'type' => 'switch', 'default' => '1', 'help' => 'रिपोर्टर सिर्फ़ /reporter/login से, बाकी स्टाफ़ सिर्फ़ एडमिन लॉगिन से। एडमिन का पता बदलना हो तो config/env.php में ADMIN_PATH।'],
        ],
    ],
    // Phase 14: चुनाव/खेल डेटा API (किसी डेटा एजेंसी या अपने स्क्रिप्ट से नतीजे/स्कोर भेजने के लिए)
    'data_api' => [
        'label' => 'डेटा API (चुनाव/खेल)', 'icon' => 'fa-plug', 'permission' => 'manage',
        'fields' => [
            'data_api_enabled' => ['label' => 'डेटा API चालू करें', 'type' => 'switch', 'default' => '0', 'help' => 'बंद हो तो /api/v1/… पर हर अनुरोध 404।'],
            'data_api_token' => ['label' => 'API टोकन (कम से कम 32 अक्षर)', 'type' => 'text', 'rules' => 'nullable|min:32|max:128|regex:/^[A-Za-z0-9_\-]+$/',
                'help' => 'हेडर में भेजें: Authorization: Bearer <टोकन>। सुझाव (नया बनाने के लिए): ' . bin2hex(random_bytes(24)) . ' · किसी से साझा न करें; लीक हो तो तुरंत बदलें।'],
        ],
    ],
    // Phase 15: बैकअप
    'backups' => [
        'label' => 'बैकअप', 'icon' => 'fa-database', 'permission' => 'manage',
        'fields' => [
            'backup_schedule' => ['label' => 'अपने-आप बैकअप', 'type' => 'select', 'options' => ['off' => 'बंद', 'daily' => 'रोज़', 'weekly' => 'हर हफ़्ते'], 'default' => 'off', 'rules' => 'required|in:off,daily,weekly', 'width' => 4,
                'help' => 'cron की ज़रूरत नहीं: साइट पर आने वाले अनुरोधों से, जवाब भेजने के बाद चलता है।'],
            'backup_schedule_type' => ['label' => 'अपने-आप बैकअप में', 'type' => 'select', 'options' => ['db' => 'सिर्फ़ डेटाबेस (हल्का)', 'full' => 'डेटाबेस + फ़ाइलें'], 'default' => 'db', 'rules' => 'required|in:db,full', 'width' => 4],
            'backup_keep' => ['label' => 'कितने बैकअप रखें', 'type' => 'number', 'default' => '7', 'rules' => 'required|integer|min:1|max:100', 'width' => 4, 'help' => 'इससे पुराने अपने-आप हटेंगे।'],
            'backup_include_private' => ['label' => 'फ़ाइल बैकअप में निजी फ़ाइलें (KYC, फ़ॉर्म अटैचमेंट) भी', 'type' => 'switch', 'default' => '1'],
        ],
    ],
    // Phase 16: वेबसाइट को फ़ोन पर ऐप की तरह इंस्टॉल करना (PWA)
    'pwa' => [
        'label' => 'ऐप (PWA)', 'icon' => 'fa-mobile-screen-button', 'permission' => 'edit',
        'fields' => [
            'pwa_enabled' => ['label' => 'PWA चालू करें (होम स्क्रीन पर इंस्टॉल, ऑफ़लाइन पढ़ना, तेज़ लोडिंग)', 'type' => 'switch', 'default' => '1', 'help' => 'HTTPS (SSL) ज़रूरी है। बंद करने पर पाठकों के फ़ोन का कैश अपने-आप साफ़ हो जाता है; वेब पुश अलग से चलता रहता है।'],
            'pwa_name' => ['label' => 'ऐप का पूरा नाम', 'type' => 'text', 'rules' => 'nullable|max:60', 'width' => 6, 'help' => 'ख़ाली = वेबसाइट का नाम'],
            'pwa_short_name' => ['label' => 'छोटा नाम (होम स्क्रीन पर आइकन के नीचे)', 'type' => 'text', 'rules' => 'nullable|max:15', 'width' => 6, 'help' => '12 अक्षर तक सबसे अच्छा'],
            'pwa_icon' => ['label' => 'ऐप आइकन', 'type' => 'image', 'width' => 4, 'help' => 'चौकोर PNG, कम से कम 512×512। ख़ाली = फ़ेविकॉन/मोबाइल लोगो से अपने-आप।'],
            'pwa_background' => ['label' => 'खुलते समय बैकग्राउंड रंग', 'type' => 'color', 'default' => '#ffffff', 'rules' => 'required|color', 'width' => 4],
            'pwa_offline_pages' => ['label' => 'ऑफ़लाइन पढ़ने के लिए हाल की कितनी ख़बरें रखें', 'type' => 'number', 'default' => '30', 'rules' => 'required|integer|min:0|max:100', 'width' => 4, 'help' => '0 = ऑफ़लाइन कॉपी नहीं (सिर्फ़ ऑफ़लाइन पेज)'],
            'pwa_install_prompt' => ['label' => 'मोबाइल पर "ऐप इंस्टॉल करें" पट्टी दिखाएँ', 'type' => 'switch', 'default' => '1', 'help' => 'दूसरी बार आने पर दिखती है; "अभी नहीं" दबाने पर 14 दिन तक नहीं।'],
        ],
    ],
    // ख़बर सुनें (Text to Speech)
    'listen' => [
        'label' => 'ख़बर सुनें (ऑडियो)', 'icon' => 'fa-headphones', 'permission' => 'manage',
        'fields' => [
            'listen_enabled' => ['label' => 'ख़बर पेज पर "ख़बर सुनें" बटन दिखाएँ', 'type' => 'switch', 'default' => '1', 'help' => 'बंद = किसी ख़बर पर नहीं। चालू होने पर हर ख़बर में अलग से चालू/बंद कर सकते हैं।'],
            'listen_default' => ['label' => 'नई ख़बर में "ख़बर सुनें" पहले से चालू रहे', 'type' => 'switch', 'default' => '1'],
            'listen_engine' => ['label' => 'आवाज़ कहाँ से', 'type' => 'select', 'options' => ['browser' => 'पाठक के फ़ोन/ब्राउज़र की आवाज़ (मुफ़्त, कोई सेटअप नहीं)', 'google' => 'Google Cloud Neural आवाज़ (सबसे इंसानी, API key ज़रूरी)'],
                'default' => 'browser', 'rules' => 'required|in:browser,google', 'width' => 6,
                'help' => 'Google: हर महीने 10 लाख अक्षर (लगभग 400-500 ख़बरें) मुफ़्त। ऑडियो एक बार बनकर सेव होता है; ख़बर बदलने पर अपने-आप नया बनता है। key न चले तो ब्राउज़र की आवाज़।'],
            'listen_rate' => ['label' => 'बोलने की गति', 'type' => 'select', 'options' => ['0.9' => 'धीमी (0.9x)', '1' => 'सामान्य (1x)', '1.1' => 'थोड़ी तेज़ (1.1x)'], 'default' => '1', 'rules' => 'required|in:0.9,1,1.1', 'width' => 6],
            'google_tts_key' => ['label' => 'Google Cloud API key (Text-to-Speech)', 'type' => 'text', 'rules' => 'nullable|max:100|regex:/^[A-Za-z0-9_\-]+$/', 'width' => 6,
                'help' => 'console.cloud.google.com → "Cloud Text-to-Speech API" चालू करें → Credentials → API key बनाएँ (उसे सिर्फ़ इसी API तक सीमित करें)।'],
            'google_tts_voice' => ['label' => 'Google आवाज़', 'type' => 'select', 'width' => 6, 'default' => 'hi-IN-Neural2-A', 'rules' => 'required|in:hi-IN-Neural2-A,hi-IN-Neural2-D,hi-IN-Neural2-B,hi-IN-Neural2-C,hi-IN-Wavenet-A,hi-IN-Wavenet-B,hi-IN-Wavenet-C,hi-IN-Wavenet-D',
                'options' => ['hi-IN-Neural2-A' => 'Neural2-A · महिला', 'hi-IN-Neural2-D' => 'Neural2-D · महिला', 'hi-IN-Neural2-B' => 'Neural2-B · पुरुष', 'hi-IN-Neural2-C' => 'Neural2-C · पुरुष',
                    'hi-IN-Wavenet-A' => 'WaveNet-A · महिला', 'hi-IN-Wavenet-D' => 'WaveNet-D · महिला', 'hi-IN-Wavenet-B' => 'WaveNet-B · पुरुष', 'hi-IN-Wavenet-C' => 'WaveNet-C · पुरुष']],
        ],
    ],
    'maintenance' => [
        'label' => 'मेंटेनेंस', 'icon' => 'fa-screwdriver-wrench', 'permission' => 'manage',
        'fields' => [
            'maintenance_mode' => ['label' => 'मेंटेनेंस मोड चालू करें (वेबसाइट बंद, एडमिन चालू)', 'type' => 'switch', 'default' => '0'],
            'maintenance_message' => ['label' => 'पाठकों के लिए संदेश', 'type' => 'textarea', 'rules' => 'nullable|max:300'],
        ],
    ],
];
